/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projeto.view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author erdle
 */
public class Frmmenu extends javax.swing.JFrame {

   public String usuariologado;
    /**
     * Creates new form Frmmenu
     */
    public Frmmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagens/fundo.jpg"));

        Image image = icon.getImage();
        painel_desktop = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(image, 0,0, getWidth(),getHeight(),this);

            }
        };
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menucontroleClientes = new javax.swing.JMenu();
        menucontroleclientes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menucontrolefuncionarios = new javax.swing.JMenuItem();
        menucontroleFornecedores = new javax.swing.JMenu();
        menucontrolefornecedores = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menucontroleestoque = new javax.swing.JMenuItem();
        menuconsultaprodutos = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menupdv = new javax.swing.JMenuItem();
        menuposicaodia = new javax.swing.JMenuItem();
        menuhistoricovendas = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        txttrocarusuario = new javax.swing.JMenuItem();
        txtsair = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle de Vendas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Usuário Logado:");

        lblusuario.setBackground(new java.awt.Color(51, 51, 255));
        lblusuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblusuario.setForeground(new java.awt.Color(51, 51, 255));
        lblusuario.setText("Caio Manheiros");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblusuario)
                .addGap(0, 619, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblusuario))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        painel_desktop.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout painel_desktopLayout = new javax.swing.GroupLayout(painel_desktop);
        painel_desktop.setLayout(painel_desktopLayout);
        painel_desktopLayout.setHorizontalGroup(
            painel_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painel_desktopLayout.setVerticalGroup(
            painel_desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_desktopLayout.createSequentialGroup()
                .addGap(0, 423, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menucontroleClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clientes.png"))); // NOI18N
        menucontroleClientes.setText("Clientes");

        menucontroleclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clientes.png"))); // NOI18N
        menucontroleclientes.setText("Controle de Clientes");
        menucontroleclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucontroleclientesActionPerformed(evt);
            }
        });
        menucontroleClientes.add(menucontroleclientes);

        jMenuBar1.add(menucontroleClientes);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionarios.png"))); // NOI18N
        jMenu3.setText("Funcionários");

        menucontrolefuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionarios.png"))); // NOI18N
        menucontrolefuncionarios.setText("Controle de Funcionários");
        menucontrolefuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucontrolefuncionariosActionPerformed(evt);
            }
        });
        jMenu3.add(menucontrolefuncionarios);

        jMenuBar1.add(jMenu3);

        menucontroleFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedores.png"))); // NOI18N
        menucontroleFornecedores.setText("Fornecedores");

        menucontrolefornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedores.png"))); // NOI18N
        menucontrolefornecedores.setText("Controle de Fornecedores");
        menucontrolefornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucontrolefornecedoresActionPerformed(evt);
            }
        });
        menucontroleFornecedores.add(menucontrolefornecedores);

        jMenuBar1.add(menucontroleFornecedores);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos.png"))); // NOI18N
        jMenu7.setText("Produtos");

        menucontroleestoque.setText("Controle de Estoque");
        menucontroleestoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucontroleestoqueActionPerformed(evt);
            }
        });
        jMenu7.add(menucontroleestoque);

        menuconsultaprodutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produtos.png"))); // NOI18N
        menuconsultaprodutos.setText("Consulta de Produtos");
        menuconsultaprodutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuconsultaprodutosActionPerformed(evt);
            }
        });
        jMenu7.add(menuconsultaprodutos);

        jMenuBar1.add(jMenu7);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas.png"))); // NOI18N
        jMenu5.setText("Vendas");

        menupdv.setText("Abrir PDV");
        menupdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupdvActionPerformed(evt);
            }
        });
        jMenu5.add(menupdv);

        menuposicaodia.setText("Posição do dia");
        menuposicaodia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuposicaodiaActionPerformed(evt);
            }
        });
        jMenu5.add(menuposicaodia);

        menuhistoricovendas.setText("Histórico de Vendas");
        menuhistoricovendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuhistoricovendasActionPerformed(evt);
            }
        });
        jMenu5.add(menuhistoricovendas);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/configuracoes.png"))); // NOI18N
        jMenu6.setText("Configurações");

        txttrocarusuario.setText("Trocar de Usuário");
        txttrocarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttrocarusuarioActionPerformed(evt);
            }
        });
        jMenu6.add(txttrocarusuario);

        jMenuBar1.add(jMenu6);

        txtsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        txtsair.setText("Sair");
        txtsair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsairMouseClicked(evt);
            }
        });
        jMenuBar1.add(txtsair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_desktop)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menucontrolefuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucontrolefuncionariosActionPerformed
        // Controle de Funcionários
           Frmfuncionarios tela = new Frmfuncionarios();
           tela.setVisible(true);
        
        
    }//GEN-LAST:event_menucontrolefuncionariosActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Deixar maximizado
        this.setExtendedState(this.MAXIMIZED_BOTH);
        lblusuario.setText(usuariologado);
        this.setVisible(true);
        
    }//GEN-LAST:event_formWindowActivated

    private void menucontroleestoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucontroleestoqueActionPerformed
        // Controle de Estoque
        FrmEstoque tela = new FrmEstoque();
        tela.setVisible(true);
    }//GEN-LAST:event_menucontroleestoqueActionPerformed

    private void menuhistoricovendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuhistoricovendasActionPerformed
        // Historico de vendas
         FrmHistorico tela = new FrmHistorico();
         tela.setVisible(true);
    }//GEN-LAST:event_menuhistoricovendasActionPerformed

    private void txttrocarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttrocarusuarioActionPerformed
        // Efetuar logout
        FrmLogin telalogin = new FrmLogin();
       
        this.dispose();
        
        telalogin.setVisible(true);
        
    }//GEN-LAST:event_txttrocarusuarioActionPerformed

    private void txtsairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsairMouseClicked
        // sair
        int op;
        op = JOptionPane.showConfirmDialog(null,"Você tem certeza que deseja sair?");
        if(op == 0){
        System.exit(0);
        }
    }//GEN-LAST:event_txtsairMouseClicked

    private void menuconsultaprodutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuconsultaprodutosActionPerformed
        // Menu consulta de Produtos
       FrmProdutos tela = new FrmProdutos();
       tela.jTabbedPane1.setSelectedIndex(1);
       tela.setVisible(true);
    }//GEN-LAST:event_menuconsultaprodutosActionPerformed

    private void menucontroleclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucontroleclientesActionPerformed
        // Controle Cliente
        Frmclientes tela = new Frmclientes();
        tela.setVisible(true);
    }//GEN-LAST:event_menucontroleclientesActionPerformed

    private void menucontrolefornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucontrolefornecedoresActionPerformed
        // Controle Fornecedores
        Frmfornecedores tela = new Frmfornecedores();
        tela.setVisible(true);
    }//GEN-LAST:event_menucontrolefornecedoresActionPerformed

    private void menupdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupdvActionPerformed
        // Pdv
         FrmVendas tela = new FrmVendas();
         tela.setVisible(true);
    }//GEN-LAST:event_menupdvActionPerformed

    private void menuposicaodiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuposicaodiaActionPerformed
        // Posição do dia
         FrmTotalVendasPorData tela = new FrmTotalVendasPorData();
         tela.setVisible(true);
    }//GEN-LAST:event_menuposicaodiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblusuario;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private javax.swing.JMenuItem menuconsultaprodutos;
    private javax.swing.JMenu menucontroleClientes;
    private javax.swing.JMenu menucontroleFornecedores;
    private javax.swing.JMenuItem menucontroleclientes;
    private javax.swing.JMenuItem menucontroleestoque;
    private javax.swing.JMenuItem menucontrolefornecedores;
    private javax.swing.JMenuItem menucontrolefuncionarios;
    public javax.swing.JMenuItem menuhistoricovendas;
    private javax.swing.JMenuItem menupdv;
    public javax.swing.JMenuItem menuposicaodia;
    private javax.swing.JDesktopPane painel_desktop;
    private javax.swing.JMenu txtsair;
    private javax.swing.JMenuItem txttrocarusuario;
    // End of variables declaration//GEN-END:variables
}
